Repository datalab-mi/moteur-de-recherche, pull requests merged in 2020-10, with the labels that each got.

#5 Changement du Makefile pour make dev avec Kibana
  Makefile
  artifacts.sample
  backend/tests/iga/test_elastic.py
  backend/tools/elastic.py
Labels: good first issue

#6 Navigateur de pièce-jointe dans la page Admin
  Makefile
  artifacts.sample
  backend/application/admin/admin_routes.py
  backend/application/common/common_routes.py
  backend/tests/bld/.env-bld
  backend/tests/bld/data/odt/création de la DNUM.odt
  backend/tests/bld/data/odt/moteur de recherche.odt
  backend/tests/bld/data/raw_expression.txt
  backend/tests/bld/test_app.py
  backend/tests/iga/.env-iga
  docker-compose-frontend-build.yml
  docker-compose-frontend-dev.yml
  frontend/rollup.config.js
  frontend/src/components/Entry.svelte
  frontend/src/components/NewItem.svelte
  frontend/src/components/ResultItem.svelte
  frontend/src/components/VirtualList.svelte
  frontend/src/components/file-browser/File.svelte
  frontend/src/components/file-browser/FileRow.svelte
  frontend/src/components/stores.js
  frontend/src/components/utils.js
  frontend/src/routes/admin.svelte
Labels: backend, enhancement, frontend

#10 Feat/docstring
  backend/application/admin/admin_routes.py
  backend/application/common/common_routes.py
  backend/tools/converter.py
  backend/tools/elastic.py
  backend/tools/utils.py
Labels: documentation

#14 Enter key pressed fires up search
  frontend/src/components/SearchBar.svelte
Labels: enhancement
